<h3>Tarefas</h3>
<? if (count($this->tarefas)): ?>
  <table class="table table-striped table-bordered table-hover">
    <tr>
      <th>Descrição</th>
      <th>Requisito</th>
      <th>Benefício</th>
      <th>Ação</th>
    </tr>
    <?
    foreach ($this->tarefas as $tarefa_realizacada):
      $tarefa = $tarefa_realizacada['tarefa'];
      $realizacao = (array_key_exists('realizacao', $tarefa_realizacada)) ? $tarefa_realizacada['realizacao'] : null;
      ?>
      <tr>
        <td>
          <h4><?= $tarefa->getNome() ?></h4>
          <?
          if (!is_null($realizacao))
            $execucao = $realizacao->getExecucao() * $realizacao->getTarefa()->getPasso();
          else
            $execucao = 0;
          ?>
          <progress value="<?= ($execucao > 100) ? 100 : $execucao ?>" max="100"> Dominado: <?= ($execucao > 100) ? 100 : $execucao ?>% </progress>
        </td>
        <td>
          Custo: <?= $tarefa->getCusto() ?>
            <? if (!$tarefa->getRequisitos()->isEmpty()): ?>
            <ul>
            <? foreach ($tarefa->getRequisitos() as $requisito): ?>
                <li>Requisito: <?= $this->partial('_partials/' . substr(get_class($requisito), strrpos(get_class($requisito), '\\') + 1) . '.phtml', array('requisito' => $requisito)); ?></li>
      <? endforeach; ?>
            </ul>
          <? endif; ?>
        </td>
        <td>
            <? if (!$tarefa->getBeneficios()->isEmpty()): ?>
            <ul>
            <? foreach ($tarefa->getBeneficios() as $beneficio): ?>
                <li><?= $this->partial('_partials/' . substr(get_class($beneficio), strrpos(get_class($beneficio), '\\') + 1) . '.phtml', array('beneficio' => $beneficio)); ?></li>
      <? endforeach; ?>
            </ul>
    <? endif; ?>
        </td>
        <td>
          <a class="button" href="<?= $this->url(array('controller' => 'index', 'action' => 'realizar', 'tarefa_id' => $tarefa->getId())); ?>">Realizar Tarefa</a>
        </td>
      </tr>
  <? endforeach; ?>
  </table>
<? endif; ?>