<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <script defer src="/js/jquery-1.8.3.min.js"></script>
  <script defer src="/js/application.admin.js"></script>
  <script src="/js/bootstrap.min.js"></script>
  <link href="/css/bootstrap.min.css" rel="stylesheet">
<!--  <link rel="stylesheet" href="/css/application.admin.css" type="text/css" />-->
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="<?= $this->url(array('controller' => 'index', 'action' => 'index'))?>">Degagogos: Admin</a>
      <ul class="nav">
        <li>
          <a href="<?= $this->url(array('controller' => 'tarefas',
              'action' => 'index', 'module' => 'admin')) ?>">
            Tarefas
          </a>
        </li>
        <li>
          <a href="<?= $this->url(array('controller' => 'itens',
                 'action' => 'index', 'module' => 'admin')) ?>">
            Itens
          </a>
        </li>
        <li>
          <a href="<?= $this->url(array('controller' => 'usuarios',
                 'action' => 'index', 'module' => 'admin')) ?>">
            Usuarios
          </a>
        </li>
             <? if (Zend_Auth::getInstance()->hasIdentity()): ?>
          <li>
            <a href="<?= $this->url(array('controller' => 'session',
                   'action' => 'logout', 'module' => 'admin')) ?>">
              Logout
            </a>
          </li>
      <? endif; ?>
      </ul>
    </div>
  </div>
   <? 
   $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('flashMessenger');
   if ($flashMessenger->hasMessages()): 
     foreach($flashMessenger->getMessages() as $message):
     ?>
  <div class="alert alert-<?=  key($message)?>">
       <button type="button" class="close" data-dismiss="alert">×</button>
       <?= current($message) ?>
      </div>
   <? endforeach;
   endif; ?>  
<?= $this->layout()->content; ?>
</body>
</html>