<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title>Demagogos</title>
    <meta charset="utf-8" />    
    <script defer src="/js/jquery-1.7.min.js"></script>
    <script defer src="/js/application.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="/css/application.css" type="text/css" />
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="#">Demagogos</a>
      <ul class="nav">
<? if (Zend_Auth::getInstance()->hasIdentity()): ?>        
        <li>
          <a href="#">Jogador: <?= $this->usuario->getNome() ?></a>
        </li>
        <li>
          <a href="#">Saldo: <?= $this->usuario->getSaldo() ?></a>
        </li>
        <li>
          <a href="#"><?= $this->placeholder('energia') ?></a>
        </li>
        
        <li>
          <a href="<?= $this->url(array('controller'=>'index','action'=>'dashboard')) ?>">Tarefas</a>
        </li>
        <li>
          <a href="<?= $this->url(array('controller'=>'index','action'=>'inventario')) ?>">Inventário</a>
        </li>
        <li>
          <a href="#">Propriedades</a>
        </li>
        <li>
          <a href="<?= $this->url(array('controller' => 'session',
                 'action' => 'logout', 'module' => 'default')) ?>">
            Logout
          </a>
        </li>
<? endif; ?>
      </ul>
    </div>
  </div>
   <? 
   $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('flashMessenger');
   if ($flashMessenger->hasMessages()): 
     foreach($flashMessenger->getMessages() as $message):
     ?>
  <div class="alert alert-<?=  key($message)?>">
       <button type="button" class="close" data-dismiss="alert">×</button>
       <?= current($message) ?>
      </div>
   <? endforeach;
   endif; ?>    
    <?=$this->layout()->content; ?>
</body>
</html>